// Section lookup: maps (activity_detail, fund) -> section
// Generated from sections.xlsx

const SECTION_MAP: { activity: string; section: string; fund: string }[] = [
  { activity: "Anhenunnaai Kudakudhinge Sikhee Haalathu Ran'galhu Kurumah Massakaiy Kurun", section: "WDC", fund: "L-CWDF" },
  { activity: "Anhenunnah Libey Vazeefaa Aai Viyafaareege Furusathuthah Fahikohdhinumah Massakaiy Kurun", section: "WDC", fund: "L-CWDF" },
  { activity: "Awareness Session Thah Beyhvun", section: "WDC", fund: "L-CWDF" },
  { activity: "Conference Hall Tharahqee Kurun", section: "WDC", fund: "L-CWDF" },
  { activity: "Insaaanee Hahquthah Rahkaatheri Kurumah Massakaiy Kurun", section: "WDC", fund: "L-CWDF" },
  { activity: "Mathee Thauleem Haasil Kuraa Anhenunge Adhadhu Ithurukurumah Massakaiy Kurun", section: "WDC", fund: "L-CWDF" },
  { activity: "Siyaasee Adhi Ijuthimaaee Kan Kamugai Anhenunge Baiverivun Ithuru Kurumah Massakaiy Kurun", section: "WDC", fund: "L-CWDF" },
  { activity: "Thafaathu Course Thah Hingun", section: "WDC", fund: "L-CWDF" },
  { activity: "1447 Vana Aharuge Fitru Zakaathaai Sadhaqaathu Faisaa Maldives Zakaathu House Ah Fonuvun", section: "Zakaath House Ah Jamaakuran Jehey", fund: "L-CPAF" },
  { activity: "1447 Vana Aharuge Tharaaveeh Namaadhukuri Haafizunge Allowance (Islamic Ministry ge faisaa)", section: "Third Party Fund", fund: "L-CTPF" },
  { activity: "2020 Vana Aharu Kandu Ulhandhu Faharuge Survey Thakaai Gulhigen Balaiganefaivaa Faisaa Public Bank Account Ah Jamaakurun", section: "PBA Ah Jamaakuran Jehey", fund: "L-CPAF" },
  { activity: "2021 Vana Aharu Kandu Ulhandhu Faharuge Survey Thakaai Gulhigen Balaiganefaivaa Faisaa Public Bank Account Ah Jamaakurun", section: "PBA Ah Jamaakuran Jehey", fund: "L-CPAF" },
  { activity: "2024 Vana Aharu Kandu Ulhandhu Faharuge Survey Thakaai Gulhigen Balaiganefaivaa Faisaa Public Bank Account Ah Jamaakurun", section: "PBA Ah Jamaakuran Jehey", fund: "L-CPAF" },
  { activity: "2024 Vana Aharu Masverikamuge Liscense Aa Kurumaa Gulhigen Balaiganefaivaa Faisaa Public Bank Account Ah Jamaakurun", section: "PBA Ah Jamaakuran Jehey", fund: "L-CPAF" },
  { activity: "2025 Vana Aharu Kandu Ulhandhu Faharuge Survey Thakaai Gulhigen Balaiganefaivaa Faisaa Public Bank Account Ah Jamaakurun", section: "PBA Ah Jamaakuran Jehey", fund: "L-CPAF" },
  { activity: "2025 Vana Aharuge Masveringe Dhuvas Faahaga Kurun", section: "Third Party Fund", fund: "L-CTPF" },
  { activity: "2026 Vana Aharuge local Council Inthihaabge Inthizaam Thakah Dey Fund", section: "Third Party Fund", fund: "L-CTPF" },
  { activity: "Airportgai Beach Hut Tharahqee Kurun", section: "WDC", fund: "L-CWDF" },
  { activity: "Ameer Ameen School Renovation Massakaiy Kurun", section: "Projects", fund: "J-LCL" },
  { activity: "Ameer Ameen School Security Belehettumaai Saafu Kurun", section: "Admin", fund: "J-GOM" },
  { activity: "Anhenunge Committee Ah Dhevey Allowance Thah", section: "WDC", fund: "L-CWDF" },
  { activity: "Anhenunge Dhuvas", section: "WDC", fund: "L-CWDF" },
  { activity: "Anti-Drug Programe Hingun", section: "Social Service", fund: "J-LCL" },
  { activity: "Archive Operationalization", section: "Library", fund: "J-GOM" },
  { activity: "Art Gallery / Museum", section: "Projects", fund: "J-LCL" },
  { activity: "Art Gallery / Museum", section: "Projects", fund: "J-GOM" },
  { activity: "Authentic Kulhudhuffushi Shop Tharahqee Kurun", section: "Projects", fund: "J-LCL" },
  { activity: "Authentic Kulhudhuffushi Shop Tharahqee Kurun", section: "Projects", fund: "J-GOM" },
  { activity: "Bandharu Thakaai, Masmaaru\u200Bkeytu, Odi ehelaa Sarahahdhu Adhi Dhathuruhiyaa Saafukoh Belehettun", section: "Municipal", fund: "J-LCL" },
  { activity: "Boaziyaaraiy Development Project", section: "Municipal", fund: "J-LCL" },
  { activity: "Boaziyaaraiy Saafukoh Belehettun", section: "Municipal", fund: "J-LCL" },
  { activity: "Boaziyaaraiy Shore Protection Project", section: "Municipal", fund: "J-LCL" },
  { activity: "Boaziyaaraiy Swimming track Tharahqee Kurun", section: "Municipal", fund: "J-LCL" },
  { activity: "Bodavaki Eco Park Tharahqee Kurun", section: "Projects", fund: "J-GOM" },
  { activity: "Bodu Muhammadhu Kaleyfaanu Ban'dharu Landscaping", section: "Projects", fund: "J-LCL" },
  { activity: "Buggy Gathumah Libifaivaa Grant (HDh. Atoll Council)", section: "Third Party Fund", fund: "L-CTPF" },
  { activity: "Business Plan Consultancy", section: "Business Development", fund: "J-LCL" },
  { activity: "Capacity Building Programme", section: "WDC", fund: "L-CWDF" },
  { activity: "Capacity Building Programme", section: "Human Resource Unit", fund: "J-GOM" },
  { activity: "City Council Ge Aharee Dhuvas Faahaga Kurun", section: "Admin", fund: "J-LCL" },
  { activity: "City Overview Video Hedhun", section: "Communication", fund: "J-LCL" },
  { activity: "Committee Ah Beynunvaa Ehenihen Kharadhuthah Kurun", section: "WDC", fund: "L-CWDF" },
  { activity: "Committee In Kuraa Ramsee Dhathuruthah", section: "WDC", fund: "L-CWDF" },
  { activity: "Communication Section Ah Beynunvaa Software Hoadhun", section: "Communication", fund: "J-GOM" },
  { activity: "Community Centre Maraamaathukoh Belehettun", section: "Sports and Civic", fund: "J-LCL" },
  { activity: "Community Centre Security Belehettun", section: "Sports and Civic", fund: "J-LCL" },
  { activity: "Community Engagement Harakaaiy Thah Hingun", section: "Library", fund: "J-LCL" },
  { activity: "Conference Hall eh Tharahqee Kurun", section: "Projects", fund: "J-LCL" },
  { activity: "Council Aai Ehenihen Muvahsasaa Thakaai Gulhigen Hingey Harakaaiythah", section: "WDC", fund: "L-CWDF" },
  { activity: "Council Idhaarage Security Belehettun", section: "Admin", fund: "J-GOM" },
  { activity: "Council Rebrand Kurumaai Guide Book", section: "Communication", fund: "J-LCL" },
  { activity: "Council Reserve Fund", section: "Council Reserve Fund", fund: "L-CRF" },
  { activity: "Council Website Redesign Kurun", section: "I.T", fund: "J-GOM" },
  { activity: "Councilge Belumuge Dhashugaivaa Than Than Maraamaathukoh Belehettun", section: "Admin", fund: "J-GOM" },
  { activity: "Councilge Project Thakaai Gulhey Video Adhi Documentation", section: "Communication", fund: "J-LCL" },
  { activity: "Councilge Vehicle Thah Maraamaathu Koh Belehettun", section: "Admin", fund: "J-GOM" },
  { activity: "Cyber Security Software", section: "I.T", fund: "J-LCL" },
  { activity: "Dhan'dhuverikamaai Gulhey Training Dhinun", section: "Environment", fund: "J-LCL" },
  { activity: "Dheenee Heyluntherikan Ithuru Kurumah Massakaiy Kurun", section: "WDC", fund: "L-CWDF" },
  { activity: "Disaster Management Plan / Climate Change Adaptation Plan Thanfeez Kurun", section: "Environment", fund: "J-LCL" },
  { activity: "Ehenihen Dhuvas Thah Faahaga Kurun", section: "WDC", fund: "L-CWDF" },
  { activity: "Ehenihen Dhuvasthah Faahaga Kurun", section: "Admin", fund: "J-LCL" },
  { activity: "Ehenihen Muvahsasaa Thakaai Gulhigen Hingey Harakaiythah", section: "Admin", fund: "J-LCL" },
  { activity: "Eid Dhuvas Faahaga Kurun", section: "WDC", fund: "L-CWDF" },
  { activity: "Eid Faahaga Kurun", section: "Sports and Civic", fund: "J-LCL" },
  { activity: "Fas Aharuge Tharahqeege Plan Ekulavailun", section: "Business Development", fund: "J-LCL" },
  { activity: "Fathuruveri kamuge Dhaairaa In Thamreenu Programme Thah Hingun", section: "Business Development", fund: "J-LCL" },
  { activity: "Fenhindaa Nizaam Tharahqee Kurun", section: "Municipal", fund: "J-LCL" },
  { activity: "Fini Fehi City Project", section: "Environment", fund: "J-LCL" },
  { activity: "Fini Maizaan Thah Tharahqee Kurun", section: "Projects", fund: "J-LCL" },
  { activity: "Fishing Platform Design Kurumaai B.O.Q Hedhun", section: "Projects", fund: "J-LCL" },
  { activity: "Foeh Maraamaathu Kurumaai Book Committee Capacity Building Programme", section: "Library", fund: "J-GOM" },
  { activity: "Food Truck (HDh. Atoll Council)", section: "Third Party Fund", fund: "L-CTPF" },
  { activity: "Fuel Storage Unit Eh Tharahqee Kurun", section: "Admin", fund: "J-GOM" },
  { activity: "G.I.S Software Training", section: "Municipal", fund: "J-LCL" },
  { activity: "Galadhun Park (Retention)", section: "Projects", fund: "J-LCL" },
  { activity: "Galadhun Park Adhi Mashi Kulhi Platform Saafu koh Belehettun", section: "Municipal", fund: "J-LCL" },
  { activity: "Gardening And Landscaping Work Force", section: "Environment", fund: "J-LCL" },
  { activity: "Geybisee Thakuge Database Farumaa Kurun", section: "Municipal", fund: "J-LCL" },
  { activity: "H.R.M Software Supply Kurun", section: "I.T/Human Resource Unit", fund: "J-GOM" },
  { activity: "Handball Mubaaraiy (Land)", section: "WDC", fund: "L-CWDF" },
  { activity: "Handball Tournament", section: "Sports and Civic", fund: "J-LCL" },
  { activity: "Harbour Office Tharahqee Kurun", section: "Projects", fund: "J-LCL" },
  { activity: "Himaayaiy Kurevifaivaa Thanthanaai Gas Gahugai Board Harukurun", section: "Environment", fund: "J-LCL" },
  { activity: "Honihiru Baazaaru Tharahqee Kurun (Phase 2)", section: "Projects", fund: "J-LCL" },
  { activity: "I.T Aai Gulhey Gothun Hoadhey Hardware", section: "I.T", fund: "J-GOM" },
  { activity: "I.T Adhi Comms Ah Beynunvaa Thakethi Hoadhun", section: "I.T/Communication", fund: "J-GOM" },
  { activity: "I.T Consultancy", section: "I.T", fund: "J-LCL" },
  { activity: "I.T Khidhumaiy Thakuge Subscription Fee Adhi Ehenihen Fee Thah Dhehkun", section: "I.T/Communication/Environment", fund: "J-GOM" },
  { activity: "I.T Tools Adhi C.C.T.V Supply Kurun", section: "I.T", fund: "J-GOM" },
  { activity: "Ibama", section: "Social Service", fund: "J-LCL" },
  { activity: "Idhaaree Hingun Harudhanaa Kurun", section: "Admin", fund: "J-GOM" },
  { activity: "Ijuthimaaee Harakai Thah Hingun", section: "Sports and Civic", fund: "J-LCL" },
  { activity: "Island Carnival", section: "Sports and Civic", fund: "J-GOM" },
  { activity: "Israhvehinah Amaazukoh Programme Thah Hingun", section: "Social Service", fund: "J-LCL" },
  { activity: "Israhvehinge Park Opening Ceremony", section: "-", fund: "J-LCL" },
  { activity: "Israhvehinge Park Tharaqqee Kurun (Pension Office)", section: "Third Party Fund", fund: "L-CTPF" },
  { activity: "Jamaa'aiy Theringe Allowance", section: "Admin/Human Resource Unit", fund: "J-GOM" },
  { activity: "Kaanu Mathiganduthah Supply Kurun", section: "Municipal", fund: "J-LCL" },
  { activity: "Kan'borani Residence Ge Faahanathah Maraamaathu Kurun", section: "Admin", fund: "J-GOM" },
  { activity: "Kashukamaa Kemeege Kankan Hamajessun", section: "Admin", fund: "J-LCL" },
  { activity: "Khaassa Ehee Aai Rahkaatherikan Beynunvaa Faraiythakah Programmethah Hingun", section: "Social Service", fund: "J-LCL" },
  { activity: "Kulhi Platform (Retention)", section: "Projects", fund: "J-LCL" },
  { activity: "Kulhivaru Mubaaraiythakah Kuraa Kharadhu", section: "Sports and Civic", fund: "J-LCL" },
  { activity: "Kulhivaru Vaseelaithah Tharahgee Kurun", section: "Sports and Civic", fund: "J-LCL" },
  { activity: "Kulhudhuffushi Championship", section: "Sports and Civic", fund: "J-LCL" },
  { activity: "Kulhudhuffushi City Aa Gulhey Fotheh Liyumaai Ekulavailun", section: "Admin", fund: "J-LCL" },
  { activity: "Kulhudhuffushi City Council ge Renovation Massakaiy Kurun", section: "Projects", fund: "J-LCL" },
  { activity: "Kulhudhuffushi City Council Ge VAPT Test Hedhun", section: "I.T", fund: "J-LCL" },
  { activity: "Kulhudhuffushi City Councilge Belumuge Dhashugaivaa Imaaraiythah Leaseline In Gulhaalun", section: "I.T", fund: "J-GOM" },
  { activity: "Kulhudhuffushi City Councilge Workshop Adhi Warehouse Eh Elhun", section: "Municipal", fund: "J-LCL" },
  { activity: "Kulhudhuffushi City Ge Dhaftharu Thah Ekulavaalun", section: "Municipal", fund: "J-GOM" },
  { activity: "Kulhudhuffushi City Thamseel Kurumah Kuraa Kharadhu", section: "Sports and Civic", fund: "J-LCL" },
  { activity: "Kulhudhuffushi Cityge Finimaizaan Thah Saafukoh Belehettun", section: "Municipal", fund: "J-LCL" },
  { activity: "Kulhudhuffushi Cityge Hulhangu Faraathu Husbinthah Saafukoh Belehettun", section: "Municipal", fund: "J-LCL" },
  { activity: "Kulhudhuffushi Cityge Irumathi Faraathu Husbinthah Saafukoh Belehettun", section: "Municipal", fund: "J-LCL" },
  { activity: "Kulhudhuffushi Cityge Rasmee Faalan Tharahqee Kurun", section: "Projects", fund: "J-LCL" },
  { activity: "Kulhudhuffushi Ship Wreck", section: "Municipal", fund: "J-LCL" },
  { activity: "Kulhudhuffushi Tharijehige Himaayaiykoh Belehehtun", section: "Projects", fund: "J-LCL" },
  { activity: "Kunbuti Portal Phase 2", section: "I.T", fund: "J-LCL" },
  { activity: "Kuneege Massala Hallu Kurun (HDh. Atoll Council)", section: "Third Party Fund", fund: "L-CTPF" },
  { activity: "Kuree Aharuge Bill Thakah Faisaa Dhekkun", section: "Finance", fund: "J-LCL" },
  { activity: "Kuree Aharuge Bill Thakah Faisaa Dhekkun", section: "WDC", fund: "L-CWDF" },
  { activity: "L.U.P Formulation", section: "Municipal", fund: "J-LCL" },
  { activity: "Library Ah Beynunvaa Fothaai Ehenigen Thakethi Hoadhun", section: "Library", fund: "J-GOM" },
  { activity: "Liyan Kiyan Dhaskohdhey Progammeh Hingun", section: "Sports and Civic", fund: "J-LCL" },
  { activity: "Local Authority Company Ge Capital", section: "Business Development", fund: "J-LCL" },
  { activity: "Local Tourism Marketing", section: "Business Development", fund: "J-LCL" },
  { activity: "Magu Bahthi Maraamaathu Kurun", section: "Admin", fund: "J-LCL" },
  { activity: "Magu Bahthi Thah Maraamaathu Kurumah Beynunvaa Thakethi Hoadhun", section: "Admin", fund: "J-LCL" },
  { activity: "Magumatheegai Beynunkuraa Board Thah Maraamaathu Koh Belehettun", section: "Municipal", fund: "J-GOM" },
  { activity: "Maguthah Maraamaathukoh Belehettun", section: "Municipal", fund: "J-LCL" },
  { activity: "Manas Hub Ah Counsellorun Hoadhun", section: "Library", fund: "J-LCL" },
  { activity: "Manas Hub Qaaimkurun", section: "Projects", fund: "J-LCL" },
  { activity: "Manashub Ah Beynunvaa Thakethi Hoadhun", section: "Social Service", fund: "J-LCL" },
  { activity: "Mas Maarukeytu Maraamaathu Koh Belehettun", section: "Admin", fund: "J-LCL" },
  { activity: "Masjidhul Haloarath Karantu Massala Hallu Kurun", section: "Admin", fund: "J-LCL" },
  { activity: "Masjidhul Haloarath Maraamaathu Kurun", section: "Admin", fund: "J-LCL" },
  { activity: "Masjidhul Hasanaath Maraamaathu Kurun", section: "Admin", fund: "J-LCL" },
  { activity: "Masjidhul Jamaa'ath Maraamaathu Kurun", section: "Admin", fund: "J-GOM" },
  { activity: "Masjidhul Muhammadh Solar Kurun (HDh. Atoll Council)", section: "Third Party Fund", fund: "L-CTPF" },
  { activity: "Masjidhul Zahuraa Maraamaathukurun", section: "Admin", fund: "J-LCL" },
  { activity: "Meeting Minutes Software Adhi Hardware", section: "I.T/Bureau", fund: "J-LCL" },
  { activity: "Mehemaanunnah Marukhabaa Dhennevun", section: "WDC", fund: "L-CWDF" },
  { activity: "Mental Health Aa Gulhey Programme Thah Hingun", section: "Social Service", fund: "J-LCL" },
  { activity: "Micro Financing Scheme", section: "Business Development", fund: "J-LCL" },
  { activity: "Miskiy Thah Maraamaathu Kurun  (Islamic Ministryge Faisa)", section: "Third Party Fund", fund: "L-CTPF" },
  { activity: "Miskiy Thakugai Vinyl Elhun", section: "Admin", fund: "J-LCL" },
  { activity: "Miskiythah Folhaa Saafukuraa Thakethi Adhi Ehenihen Thakethi Hoadhun", section: "Admin", fund: "J-LCL" },
  { activity: "Miskiythah Maraamaathu Koh Belehettun", section: "Admin", fund: "J-LCL" },
  { activity: "MLCL Subscription", section: "Admin", fund: "J-LCL" },
  { activity: "Municipal Khidhumaiy Dhinumah Beynunvaa Mini Van Hoadhun", section: "Municipal", fund: "J-GOM" },
  { activity: "Municipal Khidhumaiy Dhinumah Beynunvaa Vehicle Hoadhun", section: "Municipal", fund: "J-LCL" },
  { activity: "Municipal Section Ah Beynunvaa Thakethi Hoadhun", section: "Municipal", fund: "J-LCL" },
  { activity: "Municipal Work Force", section: "Municipal", fund: "J-LCL" },
  { activity: "Muvahzafunnah Beyhvey Eki Eki Training Programme", section: "Human Resource Unit", fund: "J-GOM" },
  { activity: "Muvahzafunnah Dhevey Musaara Aai Inaayaiy", section: "Human Resource Unit", fund: "J-GOM" },
  { activity: "Muvahzafunnah Dhevey Musaara Aai Inaayaiy", section: "Human Resource Unit", fund: "J-LCL" },
  { activity: "Nasruge Dhuvas Faahaga Kurun", section: "Admin", fund: "J-LCL" },
  { activity: "NDMA in Kulli haalaiy thakugai beynun kurumah fonuvey Faisa", section: "Third Party Fund", fund: "L-CTPF" },
  { activity: "Net Boalha Mubaaraiy Beyhvun", section: "WDC", fund: "L-CWDF" },
  { activity: "NOC Security Belehettumaai Saafu Kurun", section: "Admin", fund: "J-GOM" },
  { activity: "North Harbor, Bandaara Hiyaa  Adhi Gaburusthaan Lighting Project", section: "Municipal", fund: "J-LCL" },
  { activity: "North side Stormwater Project Phase 2", section: "Municipal", fund: "J-LCL" },
  { activity: "Odi Ehelaa Sarahahdhu Vashai Fence Jehun", section: "Projects", fund: "J-LCL" },
  { activity: "Offeehah Beynunvaa Furniture Hoadhun", section: "Admin", fund: "J-GOM" },
  { activity: "Office Hingumah Beynunvaa Capital Items Hoadhun", section: "Admin", fund: "J-GOM" },
  { activity: "Park Thakaai Maizaan Thah Maraamaathu Kurun", section: "Municipal", fund: "J-LCL" },
  { activity: "Park Tharahqee Kurun", section: "WDC", fund: "L-CWDF" },
  { activity: "Pedestrian Road Tharahqee Kurun", section: "Projects", fund: "J-LCL" },
  { activity: "Pest Control", section: "Environment", fund: "J-LCL" },
  { activity: "Plant Nursery Expansion Project", section: "Projects/Environment", fund: "J-LCL" },
  { activity: "Public Works Kharadhu (Housing Ministry)", section: "Third Party Fund", fund: "L-CTPF" },
  { activity: "Quran Mubaaraiy", section: "WDC", fund: "L-CWDF" },
  { activity: "Quran Mubaaraiy 2026 Raavaa Hingun", section: "Admin", fund: "J-LCL" },
  { activity: "Rakkaatheri Gothugai Kuni Manage Kurun (Environment Ministry)", section: "Third Party Fund", fund: "L-CTPF" },
  { activity: "Rashuge Monument", section: "Projects", fund: "J-LCL" },
  { activity: "Refundge Gothugai Dhevey Faisaa", section: "Finance", fund: "J-LCL" },
  { activity: "Retainer Basis Gai A.C Thah Maraamaathu Kurun", section: "Admin", fund: "J-GOM" },
  { activity: "Retainer Comms Firm", section: "Communication", fund: "J-GOM" },
  { activity: "Retainer I.T Firm Eh Hire Kurun", section: "I.T", fund: "J-GOM" },
  { activity: "Retainer Law Firm", section: "Legal", fund: "J-LCL" },
  { activity: "School Grant", section: "Business Development", fund: "J-LCL" },
  { activity: "Server Adhi Backup Software Supply Kurun", section: "I.T", fund: "J-GOM" },
  { activity: "Shaheed Hussain Adam Han'dhaanee Bina (Retention)", section: "Projects", fund: "J-LCL" },
  { activity: "Solar Project", section: "Projects", fund: "J-LCL" },
  { activity: "Stock Adhi Asset Management Software Phase 2", section: "I.T", fund: "J-LCL" },
  { activity: "Technical Consultancy", section: "I.T", fund: "J-LCL" },
  { activity: "Tharaaveeh Namaadhaai Dheenee Programme Thah Raavaa Hingun", section: "Admin", fund: "J-LCL" },
  { activity: "Thauleem Aai Thamreen Aa Gulhey Programme Thah Hingun", section: "Sports and Civic", fund: "J-LCL" },
  { activity: "Tourism Development Plan Consultancy", section: "Business Development", fund: "J-LCL" },
  { activity: "Traffic Awareness Programme Hingun", section: "Municipal", fund: "J-LCL" },
  { activity: "Usge Maraamaathu Kurun", section: "Admin", fund: "J-GOM" },
  { activity: "Uthuru Bandharugai Boasa Jehun", section: "Municipal", fund: "J-LCL" },
  { activity: "Uthuru Bandharugai Neru Bahthi Jehun", section: "Municipal", fund: "J-LCL" },
  { activity: "Vaavoshi Festival 2026", section: "Environment", fund: "J-LCL" },
  { activity: "VET Outreach Program 2025-2026", section: "Environment", fund: "J-LCL" },
  { activity: "Veythuve Dhiya Fas Aharu Dhuvahu Hingunu Projects Thakaai Gulhey Booklet Adhi Website Content", section: "Communication", fund: "J-LCL" },
  { activity: "Waste Management Plan Thanfeez Kurun", section: "Environment", fund: "J-LCL" },
  { activity: "Youth Center Budget (Youth Ministry)", section: "Third Party Fund", fund: "L-CTPF" },
];

// Build a lookup map keyed by normalized "activity|fund"
const sectionLookup = new Map<string, string>();
for (const entry of SECTION_MAP) {
  const key = `${entry.activity.trim().toLowerCase()}|${entry.fund.trim().toLowerCase()}`;
  sectionLookup.set(key, entry.section);
}

export function lookupSection(activityDetail: string, fund: string): string {
  const key = `${activityDetail.trim().toLowerCase()}|${fund.trim().toLowerCase()}`;
  return sectionLookup.get(key) || "";
}
